/**
 * svgIllustrationEngine.ts — Avelut Universal AI-Generated Vector Illustration System
 *
 * Provides deep multi-disciplinary domain prompting, validation, sanitization, defs injection,
 * and chalkboard drawing animations for realistic vector illustrations generated by LLMs.
 * Tailored for Avelut's warm off-white / white academic canvas.
 */

import katex from 'katex';

/**
 * Dedicated System Prompt instructing the LLM to generate rich, realistic, recognizable
 * vector illustrations from scratch with accurate scientific and academic annotations.
 */
export const SVG_REALISTIC_ILLUSTRATION_SYSTEM_PROMPT = `
================================================================================
AVELUT UNIVERSAL VECTOR ILLUSTRATION SYSTEM (TECHNICAL OUTLINE SVG ENGINE)
================================================================================
MASTER PROMPT INSTRUCTION:
"Generate a clean, minimalist technical outline illustration in valid SVG format (<svg> wrapper, no markdown block wrappers if parsing raw). Use a 400x200 viewBox, a transparent or white background, crisp strokes with light or dashed outlines for structural paths, distinct accent fills for key focal points, and clear sans-serif text labels. Use semantic classes for styling, thin strokes (stroke-width: 1.5 to 2), and a restrained professional color palette. Position all elements with precise coordinate attributes (x, y, cx, cy) to ensure exact alignment and complete responsiveness."

SEMANTIC CLASS DEFINITIONS FOR <defs><style>:
.bg { fill: transparent; }
.grid-line { stroke: rgba(255, 255, 255, 0.08); stroke-width: 1; }
.path-structural { stroke: #cbd5e1; stroke-width: 1.5; fill: none; }
.path-dashed { stroke: #94a3b8; stroke-width: 1.5; stroke-dasharray: 4, 3; fill: none; }
.path-accent { stroke: #38bdf8; stroke-width: 2; fill: none; }
.fill-node { fill: #0f172a; stroke: #38bdf8; stroke-width: 2; }
.fill-accent { fill: rgba(56, 189, 248, 0.18); stroke: #38bdf8; stroke-width: 1.5; }
.fill-subtle { fill: rgba(255, 255, 255, 0.06); stroke: #94a3b8; stroke-width: 1.5; }
.text-label { font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; font-size: 10px; fill: #ffffff; font-weight: 500; }
.text-muted { font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; font-size: 8px; fill: #94a3b8; }
.text-title { font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; font-size: 11px; fill: #38bdf8; font-weight: 600; letter-spacing: 0.5px; }

CORE DESIGN RULES:
1. COLOR PALETTE: Restrained professional palette with semantic classes (.fill-accent, .fill-subtle, .path-accent, .path-structural, .path-dashed).
2. LINE WEIGHTS: Thin, deliberate strokes (stroke-width="1.5" to "2") with semantic classes for styling.
3. TYPOGRAPHY: Rely on system sans-serif fonts (-apple-system, sans-serif) with explicit x and y coordinates and crisp label styling.
4. SCALABILITY: Always include a viewBox (viewBox="0 0 400 200") and set width="100%" height="100%" so it behaves responsively.
`;

/**
 * Standard definitions injected into every sanitized SVG
 */
const INJECTED_SVG_DEFS = `
  <defs>
    <!-- Arrowhead Markers for Dark Chalkboard Canvas -->
    <marker id="arrow" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#38BDF8" />
    </marker>
    <marker id="arrow-navy" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#FFFFFF" />
    </marker>
    <marker id="arrow-blue" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#38BDF8" />
    </marker>
    <marker id="arrow-sky" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#38BDF8" />
    </marker>
    <marker id="arrow-green" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#34D399" />
    </marker>
    <marker id="arrow-red" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#EF4444" />
    </marker>
    <marker id="arrow-amber" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#FACC15" />
    </marker>
    <marker id="arrow-purple" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#7C3AED" />
    </marker>

    <!-- Gradients Optimized for Light / Off-White Canvas -->
    <linearGradient id="grad-blue-soft" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#3B82F6" stop-opacity="0.18" />
      <stop offset="100%" stop-color="#60A5FA" stop-opacity="0.06" />
    </linearGradient>

    <linearGradient id="grad-glass" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#0284C7" stop-opacity="0.25" />
      <stop offset="50%" stop-color="#38BDF8" stop-opacity="0.10" />
      <stop offset="100%" stop-color="#0284C7" stop-opacity="0.20" />
    </linearGradient>

    <linearGradient id="grad-sky-glow" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#0066FF" stop-opacity="0.9" />
      <stop offset="100%" stop-color="#38BDF8" stop-opacity="0.6" />
    </linearGradient>

    <linearGradient id="grad-metal" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" stop-color="#CBD5E1" />
      <stop offset="50%" stop-color="#F1F5F9" />
      <stop offset="100%" stop-color="#94A3B8" />
    </linearGradient>

    <linearGradient id="grad-amber-glow" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#F59E0B" stop-opacity="0.25" />
      <stop offset="100%" stop-color="#FEF3C7" stop-opacity="0.6" />
    </linearGradient>

    <linearGradient id="grad-emerald-glow" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#10B981" stop-opacity="0.25" />
      <stop offset="100%" stop-color="#D1FAE5" stop-opacity="0.6" />
    </linearGradient>

    <linearGradient id="grad-coral-glow" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#EF4444" stop-opacity="0.25" />
      <stop offset="100%" stop-color="#FEE2E2" stop-opacity="0.6" />
    </linearGradient>

    <!-- Subtle Drop Shadow Filter for Floating Nodes & Cards -->
    <filter id="soft-shadow" x="-10%" y="-10%" width="120%" height="120%">
      <feDropShadow dx="0" dy="2" stdDeviation="3" flood-color="#0F172A" flood-opacity="0.08" />
    </filter>

    <!-- Scoped Drawing Animation -->
    <style>
    <!-- Instant Crisp Rendering (No Hand Drawing Animation) -->
    <style>
      .chalk-scene-bg, .chalk-main-object, .chalk-object-details, .chalk-vectors, .chalk-labels {
        opacity: 1;
      }
    </style>
  </defs>
`;

/**
 * Replaces standard SVG <text> tags containing LaTeX ($...$ or $$...$$)
 * with inline KaTeX rendered foreignObjects for mathematical and academic precision.
 */
function renderKatexInSvg(svgString: string): string {
    const textRegex = /<text\b([^>]*)>([\s\S]*?)<\/text>/gi;

    return svgString.replace(textRegex, (fullMatch, attrString, rawContent) => {
        const content = rawContent.trim();
        if (!content.includes('$')) {
            return fullMatch;
        }

        const getAttr = (name: string, fallback = '') => {
            const m = attrString.match(new RegExp(`${name}\\s*=\\s*["']([^"']+)["']`, 'i'));
            return m ? m[1] : fallback;
        };

        const x = parseFloat(getAttr('x', '0')) || 0;
        const y = parseFloat(getAttr('y', '0')) || 0;
        const fill = getAttr('fill', '#0F172A');
        const fontSize = getAttr('font-size', '13px');
        const textAnchor = getAttr('text-anchor', 'start').toLowerCase();
        const fontWeight = getAttr('font-weight', '600');

        let formattedHtml = content;
        try {
            formattedHtml = content.replace(/\$\$([\s\S]*?)\$\$/g, (_m: string, math: string) => {
                return katex.renderToString(math.trim(), { displayMode: false, throwOnError: false });
            });
            formattedHtml = formattedHtml.replace(/\$([^\$\n]+?)\$/g, (_m: string, math: string) => {
                return katex.renderToString(math.trim(), { displayMode: false, throwOnError: false });
            });
        } catch {
            return fullMatch;
        }

        let foWidth = 240;
        let foHeight = 44;
        let foX = x;
        let foY = y - 18;
        let justify = 'flex-start';
        let textAlign = 'left';

        if (textAnchor === 'middle') {
            foX = x - (foWidth / 2);
            justify = 'center';
            textAlign = 'center';
        } else if (textAnchor === 'end') {
            foX = x - foWidth;
            justify = 'flex-end';
            textAlign = 'right';
        }

        return `<foreignObject x="${foX}" y="${foY}" width="${foWidth}" height="${foHeight}" overflow="visible">
  <div xmlns="http://www.w3.org/1999/xhtml" style="color: ${fill}; font-size: ${fontSize}; font-family: ui-sans-serif, system-ui, -apple-system, sans-serif; font-weight: ${fontWeight}; display: flex; align-items: center; justify-content: ${justify}; text-align: ${textAlign}; width: 100%; height: 100%; pointer-events: none; line-height: 1.15;">
    ${formattedHtml}
  </div>
</foreignObject>`;
    });
}

/**
 * Validates, repairs, and sanitizes generated SVGs for safe, high-fidelity rendering.
 */
export function sanitizeAndValidateSvg(rawSvg: string | null | undefined): string | null {
    if (!rawSvg || typeof rawSvg !== 'string') return null;

    let cleaned = rawSvg.trim();

    // 1. Strip markdown code block wrappers
    cleaned = cleaned.replace(/^```(?:xml|svg|html)?\s*/i, '').replace(/```$/i, '').trim();

    // 2. Extract root <svg> ... </svg>
    const match = cleaned.match(/<svg[\s\S]*?<\/svg>/i);
    if (match) {
        cleaned = match[0];
    } else {
        const openMatch = cleaned.match(/<svg[\s\S]*/i);
        if (openMatch) {
            cleaned = `${openMatch[0]}</svg>`;
        } else {
            return null;
        }
    }

    // 3. Strip unsafe elements: <script>, <iframe>, <object>, <embed>, <applet>, <form>, <input>
    cleaned = cleaned.replace(/<\/?(?:script|iframe|object|embed|applet|form|input|meta|link)[^>]*>/gi, '');

    // 4. Strip unsafe attributes: on*, javascript:, data: (except safe images)
    cleaned = cleaned.replace(/\s+on\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi, '');
    cleaned = cleaned.replace(/href\s*=\s*["']\s*(?:javascript|vbscript):[^"']*["']/gi, 'href="#"');
    cleaned = cleaned.replace(/src\s*=\s*["']\s*(?:javascript|vbscript):[^"']*["']/gi, 'src=""');

    // 5. Ensure root attributes: viewBox, xmlns, width, height, preserveAspectRatio
    if (!cleaned.includes('viewBox')) {
        cleaned = cleaned.replace(/<svg/i, '<svg viewBox="0 0 800 480"');
    }
    if (!cleaned.includes('xmlns=')) {
        cleaned = cleaned.replace(/<svg/i, '<svg xmlns="http://www.w3.org/2000/svg"');
    }
    if (!cleaned.includes('preserveAspectRatio')) {
        cleaned = cleaned.replace(/<svg/i, '<svg preserveAspectRatio="xMidYMid meet"');
    }

    // 6. Ensure default stroke linecap & linejoin
    cleaned = cleaned.replace(/<path(?![^>]*stroke-linecap)/gi, '<path stroke-linecap="round" stroke-linejoin="round"');
    cleaned = cleaned.replace(/<line(?![^>]*stroke-linecap)/gi, '<line stroke-linecap="round" stroke-linejoin="round"');

    // 7. Inject standard defs & animation styles
    if (cleaned.includes('<defs>')) {
        cleaned = cleaned.replace(/<defs>/i, `<defs>${INJECTED_SVG_DEFS.replace('<defs>', '').replace('</defs>', '')}`);
    } else {
        cleaned = cleaned.replace(/<svg([^>]*)>/i, `<svg$1>${INJECTED_SVG_DEFS}`);
    }

    // 8. Render KaTeX math in text elements
    cleaned = renderKatexInSvg(cleaned);

    return cleaned;
}
