/**
 * Robust JSON parser and sanitizer for AI model output.
 * Handles common LLM JSON syntax issues such as missing commas,
 * trailing commas, unescaped newlines, markdown code blocks, and truncated JSON output.
 */

export interface ParseOptions<T = any> {
  fallback?: T;
  expectArray?: boolean;
}

/**
 * Sanitizes raw string output from AI models before JSON parsing.
 */
export function sanitizeJsonString(raw: string, expectArray: boolean = false): string {
  if (!raw) return '';

  let cleaned = raw.trim();

  // Strip markdown code fences if present
  const fenceMatch = cleaned.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
  if (fenceMatch && fenceMatch[1]) {
    cleaned = fenceMatch[1].trim();
  } else {
    cleaned = cleaned.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();
  }

  // Find structural boundaries
  const startChar = expectArray ? '[' : '{';
  const endChar = expectArray ? ']' : '}';

  let firstIndex = cleaned.indexOf(startChar);
  if (!expectArray && (firstIndex === -1 || (cleaned.indexOf('[') !== -1 && cleaned.indexOf('[') < firstIndex))) {
    // If not explicitly expecting an array, check if array comes earlier
    const firstBrace = cleaned.indexOf('{');
    const firstBracket = cleaned.indexOf('[');
    if (firstBracket !== -1 && (firstBrace === -1 || firstBracket < firstBrace)) {
      firstIndex = firstBracket;
    }
  }

  const lastIndex = cleaned.lastIndexOf(cleaned[firstIndex] === '[' ? ']' : '}');

  if (firstIndex !== -1 && lastIndex !== -1 && lastIndex > firstIndex) {
    cleaned = cleaned.substring(firstIndex, lastIndex + 1);
  } else if (firstIndex !== -1) {
    cleaned = cleaned.substring(firstIndex);
  }

  return cleaned;
}

/**
 * Attempts to repair broken JSON string generated by LLMs.
 */
export function repairJsonString(jsonStr: string): string {
  if (!jsonStr) return jsonStr;

  let fixed = jsonStr;

  // 1. Remove trailing commas before closing braces/brackets
  fixed = fixed.replace(/,\s*([\}\]])/g, '$1');

  // 2. Fix missing commas between key-value pairs or array elements
  // e.g. "val1"\n"key2": -> "val1",\n"key2":
  fixed = fixed.replace(/(["\d\]\}true|false|null])\s*\n\s*(["\{])/gi, '$1,\n$2');
  // e.g. } { -> }, {
  fixed = fixed.replace(/\}\s*\{/g, '},{');
  // e.g. ] [ -> ], [
  fixed = fixed.replace(/\]\s*\[/g, '],[');
  // e.g. } " -> }, "
  fixed = fixed.replace(/\}\s*"/g, '},"');
  // e.g. ] " -> ], "
  fixed = fixed.replace(/\]\s*"/g, '],"');

  // 3. Normalize unescaped newlines inside string literals
  let inString = false;
  let isEscaped = false;
  let charArray: string[] = [];

  for (let i = 0; i < fixed.length; i++) {
    const ch = fixed[i];

    if (inString) {
      if (isEscaped) {
        if (ch === '"' || ch === '\\' || ch === '/' || ch === 'b' || ch === 'f' || ch === 'n' || ch === 'r' || ch === 't' || ch === 'u') {
          charArray.push('\\' + ch);
        } else {
          charArray.push('\\\\' + ch);
        }
        isEscaped = false;
      } else if (ch === '\\') {
        isEscaped = true;
      } else if (ch === '"') {
        inString = false;
        charArray.push(ch);
      } else if (ch === '\n') {
        charArray.push('\\n');
      } else if (ch === '\r') {
        charArray.push('\\r');
      } else if (ch === '\t') {
        charArray.push('\\t');
      } else {
        charArray.push(ch);
      }
    } else {
      if (ch === '"') {
        inString = true;
        charArray.push(ch);
      } else {
        charArray.push(ch);
      }
    }
  }

  let repaired = charArray.join('');

  // 4. Auto-close truncated JSON structure if truncated
  const stack: string[] = [];
  inString = false;
  isEscaped = false;

  for (let i = 0; i < repaired.length; i++) {
    const ch = repaired[i];
    if (inString) {
      if (isEscaped) {
        isEscaped = false;
      } else if (ch === '\\') {
        isEscaped = true;
      } else if (ch === '"') {
        inString = false;
      }
    } else {
      if (ch === '"') {
        inString = true;
      } else if (ch === '{' || ch === '[') {
        stack.push(ch === '{' ? '}' : ']');
      } else if (ch === '}' || ch === ']') {
        if (stack.length > 0 && stack[stack.length - 1] === ch) {
          stack.pop();
        }
      }
    }
  }

  // If string ended open, close quote
  if (inString) {
    repaired += '"';
  }

  // Clean any hanging trailing comma after closing string
  repaired = repaired.replace(/,\s*$/, '');

  // Close remaining open brackets/braces in reverse order
  while (stack.length > 0) {
    repaired += stack.pop();
  }

  return repaired;
}

/**
 * Safely parses JSON string with multi-stage repair and fallback support.
 */
export function cleanAndParseJson<T = any>(rawText: string, options?: ParseOptions<T> | T): T {
  const fallback = (options && typeof options === 'object' && 'fallback' in options)
    ? options.fallback
    : (options as T);
  const expectArray = (options && typeof options === 'object' && 'expectArray' in options)
    ? options.expectArray
    : false;

  if (!rawText || typeof rawText !== 'string') {
    if (fallback !== undefined) return fallback;
    throw new Error('cleanAndParseJson: empty or non-string input provided.');
  }

  const sanitized = sanitizeJsonString(rawText, expectArray);

  // Pass 1: Direct JSON.parse
  try {
    return JSON.parse(sanitized) as T;
  } catch (_) {
    // Continue to repair
  }

  // Pass 2: Repaired JSON.parse
  try {
    const repaired = repairJsonString(sanitized);
    return JSON.parse(repaired) as T;
  } catch (repairErr: any) {
    // Pass 3: Extra aggressive repair - trailing comma removal and quote fix
    try {
      const ultraRepaired = sanitized
        .replace(/,\s*([\}\]])/g, '$1')
        .replace(/([{,]\s*)([a-zA-Z0-9_]+)\s*:/g, '$1"$2":'); // Quote unquoted keys
      return JSON.parse(ultraRepaired) as T;
    } catch (_) {
      // If a fallback was provided, return fallback instead of throwing
      if (fallback !== undefined) {
        console.warn('[cleanAndParseJson] Parsing failed, using fallback structure.', repairErr);
        return fallback;
      }
      throw new Error(`Failed to parse AI JSON response: ${repairErr?.message || 'Invalid JSON syntax'}`);
    }
  }
}
